services:
  - name: express-server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    buildCommand: npm install
    startCommand: npm run swagger
    github:
      branch: master