# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: RUN_SERVER

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

env:
  MongoDBUserName: ${{ secrets.MongoDBUserName }}
  MongoDBPassword: ${{ secrets.MongoDBPassword }}
  MongoDBdataBase: ${{ secrets.MongoDBdataBase }}
  EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS   }}
  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD  }}
  JWT_SECRET: ${{ secrets.JWT_SECRET      }}
  BasedUrl: ${{ secrets.BasedUrl        }}
  SWAGGERADMI: ${{ secrets.SWAGGERADMI     }}
  SWAGGERUSER: ${{ secrets.SWAGGERUSER     }}
  SWAGGERPASSWORD: ${{ secrets.SWAGGERPASSWORD }}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run test

      - name: Install Newman
        run: npm install -g newman

      - name: run the server
        run: node  ./server.js

      - name: Start the Server
        run: |
          nohup node ./server.js > server_output.log &
          sleep 5

      - name: Wait for Server to Be Ready
        run: |
          RETRY=0
          MAX_RETRIES=20
          while [ $RETRY -lt $MAX_RETRIES ]; do
            HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:5000/health-care)
            if [ "$HTTP_STATUS" -eq 200 ]; then
              echo "Server is ready!"
              break
            fi
            RETRY=$((RETRY + 1))
            sleep 2  # Wait 2 seconds before retrying
          done

      - name: Run Newman Tests
        run:  npm run newman