# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: RUN_SERVER

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

env:
  MongoDBUserName: ${{ secrets.MongoDBUserName }}
  MongoDBPassword: ${{ secrets.MongoDBPassword }}
  MongoDBdataBase: ${{ secrets.MongoDBdataBase }}
  EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS   }}
  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD  }}
  JWT_SECRET: ${{ secrets.JWT_SECRET      }}
  BasedUrl: ${{ secrets.BasedUrl        }}
  SWAGGERADMI: ${{ secrets.SWAGGERADMI     }}
  SWAGGERUSER: ${{ secrets.SWAGGERUSER     }}
  SWAGGERPASSWORD: ${{ secrets.SWAGGERPASSWORD }}
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      deployment_url: ${{ steps.set_url.outputs.deployment_url }}
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run test

  newman:
    needs: build 
    runs-on: ubuntu-latest

    steps:
      - name: Install Newman
        run: npm install -g newman

      - name: run the server
        run: npm run swagger

      - name: Run Postman Tests with Newman
        run:  npm run newman