name: Multi-Stage Workflow with Node.js, Server, and Newman Tests

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Jest Tests
        run: npm run test

  run_server:
    needs: install_and_test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Start the Server
        run: |
          nohup node ./server.js > server_output.log &
          sleep 5

      - name: Wait for Server to Be Ready
        run: |
          RETRY=0
          MAX_RETRIES=20
          while [ $RETRY -lt $MAX_RETRIES ]; do
            HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:5000/health-care)
            if [ "$HTTP_STATUS" -eq 200 ]; then
              echo "Server is ready!"
              break
            fi
            RETRY=$((RETRY + 1))
            sleep 2  # Wait 2 seconds before retrying
          done

  run_newman:
    needs: run_server
    runs-on: ubuntu-latest

    steps:
      - name: Install Newman
        run: npm install -g newman

      - name: Run Newman Tests
        run: newman run __test__/postmen/HEALTHCARE.postman_collection.json --env-var baseurl=http://localhost:5000
